development:
  adapter: postgresql
  database: db/irc_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/irc_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/irc_production
  pool: 5
  timeout: 5000
